// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: coordsproto/coords.proto

package coordsproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorRequest) Reset() {
	*x = SensorRequest{}
	mi := &file_coordsproto_coords_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorRequest) ProtoMessage() {}

func (x *SensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordsproto_coords_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorRequest.ProtoReflect.Descriptor instead.
func (*SensorRequest) Descriptor() ([]byte, []int) {
	return file_coordsproto_coords_proto_rawDescGZIP(), []int{0}
}

type SensorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	X1            float64                `protobuf:"fixed64,2,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            float64                `protobuf:"fixed64,3,opt,name=y1,proto3" json:"y1,omitempty"`
	Z1            float64                `protobuf:"fixed64,4,opt,name=z1,proto3" json:"z1,omitempty"`
	Vx1           float64                `protobuf:"fixed64,5,opt,name=vx1,proto3" json:"vx1,omitempty"`
	Vy1           float64                `protobuf:"fixed64,6,opt,name=vy1,proto3" json:"vy1,omitempty"`
	Vz1           float64                `protobuf:"fixed64,7,opt,name=vz1,proto3" json:"vz1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorResponse) Reset() {
	*x = SensorResponse{}
	mi := &file_coordsproto_coords_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorResponse) ProtoMessage() {}

func (x *SensorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordsproto_coords_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorResponse.ProtoReflect.Descriptor instead.
func (*SensorResponse) Descriptor() ([]byte, []int) {
	return file_coordsproto_coords_proto_rawDescGZIP(), []int{1}
}

func (x *SensorResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *SensorResponse) GetX1() float64 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *SensorResponse) GetY1() float64 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *SensorResponse) GetZ1() float64 {
	if x != nil {
		return x.Z1
	}
	return 0
}

func (x *SensorResponse) GetVx1() float64 {
	if x != nil {
		return x.Vx1
	}
	return 0
}

func (x *SensorResponse) GetVy1() float64 {
	if x != nil {
		return x.Vy1
	}
	return 0
}

func (x *SensorResponse) GetVz1() float64 {
	if x != nil {
		return x.Vz1
	}
	return 0
}

var File_coordsproto_coords_proto protoreflect.FileDescriptor

const file_coordsproto_coords_proto_rawDesc = "" +
	"\n" +
	"\x18coordsproto/coords.proto\x12\vcoordsproto\"\x0f\n" +
	"\rSensorRequest\"\x8a\x01\n" +
	"\x0eSensorResponse\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12\x0e\n" +
	"\x02x1\x18\x02 \x01(\x01R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x03 \x01(\x01R\x02y1\x12\x0e\n" +
	"\x02z1\x18\x04 \x01(\x01R\x02z1\x12\x10\n" +
	"\x03vx1\x18\x05 \x01(\x01R\x03vx1\x12\x10\n" +
	"\x03vy1\x18\x06 \x01(\x01R\x03vy1\x12\x10\n" +
	"\x03vz1\x18\a \x01(\x01R\x03vz12U\n" +
	"\rSensorService\x12D\n" +
	"\tGetSensor\x12\x1a.coordsproto.SensorRequest\x1a\x1b.coordsproto.SensorResponseB\x0fZ\r./coordsprotob\x06proto3"

var (
	file_coordsproto_coords_proto_rawDescOnce sync.Once
	file_coordsproto_coords_proto_rawDescData []byte
)

func file_coordsproto_coords_proto_rawDescGZIP() []byte {
	file_coordsproto_coords_proto_rawDescOnce.Do(func() {
		file_coordsproto_coords_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordsproto_coords_proto_rawDesc), len(file_coordsproto_coords_proto_rawDesc)))
	})
	return file_coordsproto_coords_proto_rawDescData
}

var file_coordsproto_coords_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_coordsproto_coords_proto_goTypes = []any{
	(*SensorRequest)(nil),  // 0: coordsproto.SensorRequest
	(*SensorResponse)(nil), // 1: coordsproto.SensorResponse
}
var file_coordsproto_coords_proto_depIdxs = []int32{
	0, // 0: coordsproto.SensorService.GetSensor:input_type -> coordsproto.SensorRequest
	1, // 1: coordsproto.SensorService.GetSensor:output_type -> coordsproto.SensorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_coordsproto_coords_proto_init() }
func file_coordsproto_coords_proto_init() {
	if File_coordsproto_coords_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordsproto_coords_proto_rawDesc), len(file_coordsproto_coords_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordsproto_coords_proto_goTypes,
		DependencyIndexes: file_coordsproto_coords_proto_depIdxs,
		MessageInfos:      file_coordsproto_coords_proto_msgTypes,
	}.Build()
	File_coordsproto_coords_proto = out.File
	file_coordsproto_coords_proto_goTypes = nil
	file_coordsproto_coords_proto_depIdxs = nil
}
