// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/flightbook.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlightbookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightbookRequest) Reset() {
	*x = FlightbookRequest{}
	mi := &file_proto_flightbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightbookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightbookRequest) ProtoMessage() {}

func (x *FlightbookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flightbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightbookRequest.ProtoReflect.Descriptor instead.
func (*FlightbookRequest) Descriptor() ([]byte, []int) {
	return file_proto_flightbook_proto_rawDescGZIP(), []int{0}
}

type FlightbookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T             string                 `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"`
	Text1         string                 `protobuf:"bytes,2,opt,name=text1,proto3" json:"text1,omitempty"`
	Text2         string                 `protobuf:"bytes,3,opt,name=text2,proto3" json:"text2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightbookResponse) Reset() {
	*x = FlightbookResponse{}
	mi := &file_proto_flightbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightbookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightbookResponse) ProtoMessage() {}

func (x *FlightbookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flightbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightbookResponse.ProtoReflect.Descriptor instead.
func (*FlightbookResponse) Descriptor() ([]byte, []int) {
	return file_proto_flightbook_proto_rawDescGZIP(), []int{1}
}

func (x *FlightbookResponse) GetT() string {
	if x != nil {
		return x.T
	}
	return ""
}

func (x *FlightbookResponse) GetText1() string {
	if x != nil {
		return x.Text1
	}
	return ""
}

func (x *FlightbookResponse) GetText2() string {
	if x != nil {
		return x.Text2
	}
	return ""
}

var File_proto_flightbook_proto protoreflect.FileDescriptor

const file_proto_flightbook_proto_rawDesc = "" +
	"\n" +
	"\x16proto/flightbook.proto\x12\x0fflightbookproto\"\x13\n" +
	"\x11FlightbookRequest\"N\n" +
	"\x12FlightbookResponse\x12\f\n" +
	"\x01t\x18\x01 \x01(\tR\x01t\x12\x14\n" +
	"\x05text1\x18\x02 \x01(\tR\x05text1\x12\x14\n" +
	"\x05text2\x18\x03 \x01(\tR\x05text22m\n" +
	"\x11FlightbookService\x12X\n" +
	"\rGetFlightbook\x12\".flightbookproto.FlightbookRequest\x1a#.flightbookproto.FlightbookResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_flightbook_proto_rawDescOnce sync.Once
	file_proto_flightbook_proto_rawDescData []byte
)

func file_proto_flightbook_proto_rawDescGZIP() []byte {
	file_proto_flightbook_proto_rawDescOnce.Do(func() {
		file_proto_flightbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_flightbook_proto_rawDesc), len(file_proto_flightbook_proto_rawDesc)))
	})
	return file_proto_flightbook_proto_rawDescData
}

var file_proto_flightbook_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_flightbook_proto_goTypes = []any{
	(*FlightbookRequest)(nil),  // 0: flightbookproto.FlightbookRequest
	(*FlightbookResponse)(nil), // 1: flightbookproto.FlightbookResponse
}
var file_proto_flightbook_proto_depIdxs = []int32{
	0, // 0: flightbookproto.FlightbookService.GetFlightbook:input_type -> flightbookproto.FlightbookRequest
	1, // 1: flightbookproto.FlightbookService.GetFlightbook:output_type -> flightbookproto.FlightbookResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_flightbook_proto_init() }
func file_proto_flightbook_proto_init() {
	if File_proto_flightbook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_flightbook_proto_rawDesc), len(file_proto_flightbook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_flightbook_proto_goTypes,
		DependencyIndexes: file_proto_flightbook_proto_depIdxs,
		MessageInfos:      file_proto_flightbook_proto_msgTypes,
	}.Build()
	File_proto_flightbook_proto = out.File
	file_proto_flightbook_proto_goTypes = nil
	file_proto_flightbook_proto_depIdxs = nil
}
