// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/flightbook.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlightbookService_GetFlightbook_FullMethodName = "/flightbookproto.FlightbookService/GetFlightbook"
)

// FlightbookServiceClient is the client API for FlightbookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlightbookServiceClient interface {
	GetFlightbook(ctx context.Context, in *FlightbookRequest, opts ...grpc.CallOption) (*FlightbookResponse, error)
}

type flightbookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlightbookServiceClient(cc grpc.ClientConnInterface) FlightbookServiceClient {
	return &flightbookServiceClient{cc}
}

func (c *flightbookServiceClient) GetFlightbook(ctx context.Context, in *FlightbookRequest, opts ...grpc.CallOption) (*FlightbookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlightbookResponse)
	err := c.cc.Invoke(ctx, FlightbookService_GetFlightbook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlightbookServiceServer is the server API for FlightbookService service.
// All implementations must embed UnimplementedFlightbookServiceServer
// for forward compatibility.
type FlightbookServiceServer interface {
	GetFlightbook(context.Context, *FlightbookRequest) (*FlightbookResponse, error)
	mustEmbedUnimplementedFlightbookServiceServer()
}

// UnimplementedFlightbookServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlightbookServiceServer struct{}

func (UnimplementedFlightbookServiceServer) GetFlightbook(context.Context, *FlightbookRequest) (*FlightbookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlightbook not implemented")
}
func (UnimplementedFlightbookServiceServer) mustEmbedUnimplementedFlightbookServiceServer() {}
func (UnimplementedFlightbookServiceServer) testEmbeddedByValue()                           {}

// UnsafeFlightbookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlightbookServiceServer will
// result in compilation errors.
type UnsafeFlightbookServiceServer interface {
	mustEmbedUnimplementedFlightbookServiceServer()
}

func RegisterFlightbookServiceServer(s grpc.ServiceRegistrar, srv FlightbookServiceServer) {
	// If the following call pancis, it indicates UnimplementedFlightbookServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlightbookService_ServiceDesc, srv)
}

func _FlightbookService_GetFlightbook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlightbookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightbookServiceServer).GetFlightbook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightbookService_GetFlightbook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightbookServiceServer).GetFlightbook(ctx, req.(*FlightbookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlightbookService_ServiceDesc is the grpc.ServiceDesc for FlightbookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlightbookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flightbookproto.FlightbookService",
	HandlerType: (*FlightbookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFlightbook",
			Handler:    _FlightbookService_GetFlightbook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/flightbook.proto",
}
