// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: tempsproto/temps.proto

package tempsproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorRequest) Reset() {
	*x = SensorRequest{}
	mi := &file_tempsproto_temps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorRequest) ProtoMessage() {}

func (x *SensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tempsproto_temps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorRequest.ProtoReflect.Descriptor instead.
func (*SensorRequest) Descriptor() ([]byte, []int) {
	return file_tempsproto_temps_proto_rawDescGZIP(), []int{0}
}

type SensorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	T1            float64                `protobuf:"fixed64,2,opt,name=t1,proto3" json:"t1,omitempty"`
	H1            float64                `protobuf:"fixed64,3,opt,name=h1,proto3" json:"h1,omitempty"`
	T2            float64                `protobuf:"fixed64,4,opt,name=t2,proto3" json:"t2,omitempty"`
	H2            float64                `protobuf:"fixed64,5,opt,name=h2,proto3" json:"h2,omitempty"`
	T3            float64                `protobuf:"fixed64,6,opt,name=t3,proto3" json:"t3,omitempty"`
	H3            float64                `protobuf:"fixed64,7,opt,name=h3,proto3" json:"h3,omitempty"`
	T4            float64                `protobuf:"fixed64,8,opt,name=t4,proto3" json:"t4,omitempty"`
	H4            float64                `protobuf:"fixed64,9,opt,name=h4,proto3" json:"h4,omitempty"`
	T5            float64                `protobuf:"fixed64,10,opt,name=t5,proto3" json:"t5,omitempty"`
	H5            float64                `protobuf:"fixed64,11,opt,name=h5,proto3" json:"h5,omitempty"`
	T6            float64                `protobuf:"fixed64,12,opt,name=t6,proto3" json:"t6,omitempty"`
	H6            float64                `protobuf:"fixed64,13,opt,name=h6,proto3" json:"h6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorResponse) Reset() {
	*x = SensorResponse{}
	mi := &file_tempsproto_temps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorResponse) ProtoMessage() {}

func (x *SensorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tempsproto_temps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorResponse.ProtoReflect.Descriptor instead.
func (*SensorResponse) Descriptor() ([]byte, []int) {
	return file_tempsproto_temps_proto_rawDescGZIP(), []int{1}
}

func (x *SensorResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *SensorResponse) GetT1() float64 {
	if x != nil {
		return x.T1
	}
	return 0
}

func (x *SensorResponse) GetH1() float64 {
	if x != nil {
		return x.H1
	}
	return 0
}

func (x *SensorResponse) GetT2() float64 {
	if x != nil {
		return x.T2
	}
	return 0
}

func (x *SensorResponse) GetH2() float64 {
	if x != nil {
		return x.H2
	}
	return 0
}

func (x *SensorResponse) GetT3() float64 {
	if x != nil {
		return x.T3
	}
	return 0
}

func (x *SensorResponse) GetH3() float64 {
	if x != nil {
		return x.H3
	}
	return 0
}

func (x *SensorResponse) GetT4() float64 {
	if x != nil {
		return x.T4
	}
	return 0
}

func (x *SensorResponse) GetH4() float64 {
	if x != nil {
		return x.H4
	}
	return 0
}

func (x *SensorResponse) GetT5() float64 {
	if x != nil {
		return x.T5
	}
	return 0
}

func (x *SensorResponse) GetH5() float64 {
	if x != nil {
		return x.H5
	}
	return 0
}

func (x *SensorResponse) GetT6() float64 {
	if x != nil {
		return x.T6
	}
	return 0
}

func (x *SensorResponse) GetH6() float64 {
	if x != nil {
		return x.H6
	}
	return 0
}

var File_tempsproto_temps_proto protoreflect.FileDescriptor

const file_tempsproto_temps_proto_rawDesc = "" +
	"\n" +
	"\x16tempsproto/temps.proto\x12\n" +
	"tempsproto\"\x0f\n" +
	"\rSensorRequest\"\xe4\x01\n" +
	"\x0eSensorResponse\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12\x0e\n" +
	"\x02t1\x18\x02 \x01(\x01R\x02t1\x12\x0e\n" +
	"\x02h1\x18\x03 \x01(\x01R\x02h1\x12\x0e\n" +
	"\x02t2\x18\x04 \x01(\x01R\x02t2\x12\x0e\n" +
	"\x02h2\x18\x05 \x01(\x01R\x02h2\x12\x0e\n" +
	"\x02t3\x18\x06 \x01(\x01R\x02t3\x12\x0e\n" +
	"\x02h3\x18\a \x01(\x01R\x02h3\x12\x0e\n" +
	"\x02t4\x18\b \x01(\x01R\x02t4\x12\x0e\n" +
	"\x02h4\x18\t \x01(\x01R\x02h4\x12\x0e\n" +
	"\x02t5\x18\n" +
	" \x01(\x01R\x02t5\x12\x0e\n" +
	"\x02h5\x18\v \x01(\x01R\x02h5\x12\x0e\n" +
	"\x02t6\x18\f \x01(\x01R\x02t6\x12\x0e\n" +
	"\x02h6\x18\r \x01(\x01R\x02h62S\n" +
	"\rSensorService\x12B\n" +
	"\tGetSensor\x12\x19.tempsproto.SensorRequest\x1a\x1a.tempsproto.SensorResponseB\x0eZ\f./tempsprotob\x06proto3"

var (
	file_tempsproto_temps_proto_rawDescOnce sync.Once
	file_tempsproto_temps_proto_rawDescData []byte
)

func file_tempsproto_temps_proto_rawDescGZIP() []byte {
	file_tempsproto_temps_proto_rawDescOnce.Do(func() {
		file_tempsproto_temps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tempsproto_temps_proto_rawDesc), len(file_tempsproto_temps_proto_rawDesc)))
	})
	return file_tempsproto_temps_proto_rawDescData
}

var file_tempsproto_temps_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tempsproto_temps_proto_goTypes = []any{
	(*SensorRequest)(nil),  // 0: tempsproto.SensorRequest
	(*SensorResponse)(nil), // 1: tempsproto.SensorResponse
}
var file_tempsproto_temps_proto_depIdxs = []int32{
	0, // 0: tempsproto.SensorService.GetSensor:input_type -> tempsproto.SensorRequest
	1, // 1: tempsproto.SensorService.GetSensor:output_type -> tempsproto.SensorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tempsproto_temps_proto_init() }
func file_tempsproto_temps_proto_init() {
	if File_tempsproto_temps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tempsproto_temps_proto_rawDesc), len(file_tempsproto_temps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tempsproto_temps_proto_goTypes,
		DependencyIndexes: file_tempsproto_temps_proto_depIdxs,
		MessageInfos:      file_tempsproto_temps_proto_msgTypes,
	}.Build()
	File_tempsproto_temps_proto = out.File
	file_tempsproto_temps_proto_goTypes = nil
	file_tempsproto_temps_proto_depIdxs = nil
}
