networks:
  monitoring:
    driver: host

services:
  producercoords:
    image: producercoords:v5
    container_name: producercoords
    environment:
      ADDRESS_METRICS: 0.0.0.0:2223
      ADDRESS_GRPC: gencoords:50070
      ADDRESS_KAFKA: kafka01:9092
      OTEL_EXPORTER_OTLP_ENDPOINT: otel01:4317
    ports:
      - 9070:9070 # API
      - 2223:2223
    restart: unless-stopped
